require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/**/*.rb'

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/EndOfLine:
  EnforcedStyle: lf
  Enabled: False
  