version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          BUNDLER_VERSION: 2.0.1


cashes:
  - &bundle_caches_v1 v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_caches_v1
            - *bundle_cache
      - run: sudo apt-get install cmake && bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubucop
          command: bundle exec rubocop
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec --format progress
      - store_artifacts:
          path: /tmp/test-results

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering
